import { PrismaClient } from '@prisma/client';
import { createHash } from 'crypto';

const prisma = new PrismaClient();

function generateFingerprint(url: string): string {
  return createHash('sha256').update(url).digest('hex');
}

async function main() {
  // Clear existing jobs
  await prisma.jobListing.deleteMany({});

  const jobs = [
    {
      externalId: 'li-001',
      platform: 'linkedin' as const,
      title: 'Senior Product Manager',
      companyName: 'Airbnb',
      companyLogoUrl: 'https://logo.clearbit.com/airbnb.com',
      location: 'San Francisco, CA',
      isRemote: true,
      salaryMin: 150000,
      salaryMax: 200000,
      salaryCurrency: 'USD',
      salaryPeriod: 'year',
      description: `We're looking for an experienced Product Manager to lead our growth initiatives. You'll work with a talented team to define product strategy, prioritize features, and drive user engagement. 5+ years of PM experience required. Experience with marketplaces is a plus.`,
      applicationUrl: 'https://linkedin.com/jobs/view/li-001',
      atsType: 'linkedin',
      isGhostJob: false,
      postedAt: new Date('2024-03-01'),
      expiresAt: null,
      urlFingerprint: generateFingerprint('https://linkedin.com/jobs/view/li-001'),
    },
    {
      externalId: 'ind-002',
      platform: 'indeed' as const,
      title: 'Full Stack Engineer',
      companyName: 'Stripe',
      companyLogoUrl: 'https://logo.clearbit.com/stripe.com',
      location: 'Remote',
      isRemote: true,
      salaryMin: 160000,
      salaryMax: 210000,
      salaryCurrency: 'USD',
      salaryPeriod: 'year',
      description: `Build payment infrastructure that powers the internet. We're hiring full stack engineers to work on core platform features. Strong TypeScript/React and backend experience required. 3+ years minimum.`,
      applicationUrl: 'https://indeed.com/jobs/ind-002',
      atsType: 'greenhouse',
      isGhostJob: false,
      postedAt: new Date('2024-03-02'),
      expiresAt: null,
      urlFingerprint: generateFingerprint('https://indeed.com/jobs/ind-002'),
    },
    {
      externalId: 'gh-003',
      platform: 'glassdoor' as const,
      title: 'Data Scientist',
      companyName: 'Google',
      companyLogoUrl: 'https://logo.clearbit.com/google.com',
      location: 'Mountain View, CA',
      isRemote: false,
      salaryMin: 140000,
      salaryMax: 190000,
      salaryCurrency: 'USD',
      salaryPeriod: 'year',
      description: `Join Google's AI/ML team to work on cutting-edge machine learning projects. We need experienced data scientists with strong Python skills and ML background. PhD or equivalent experience preferred.`,
      applicationUrl: 'https://google.com/careers/gh-003',
      atsType: 'greenhouse',
      isGhostJob: false,
      postedAt: new Date('2024-03-03'),
      expiresAt: null,
      urlFingerprint: generateFingerprint('https://google.com/careers/gh-003'),
    },
    {
      externalId: 'ng-004',
      platform: 'naukrigulf' as const,
      title: 'Senior DevOps Engineer',
      companyName: 'Emirates NBD',
      companyLogoUrl: 'https://logo.clearbit.com/emiratesnbd.com',
      location: 'Dubai, UAE',
      isRemote: false,
      salaryMin: 120000,
      salaryMax: 160000,
      salaryCurrency: 'AED',
      salaryPeriod: 'year',
      description: `Emirates NBD is hiring a Senior DevOps Engineer to manage our cloud infrastructure. Kubernetes, Docker, and AWS expertise required. 5+ years in DevOps roles. Relocation package available.`,
      applicationUrl: 'https://naukrigulf.com/jobs/ng-004',
      atsType: 'taleo',
      isGhostJob: false,
      postedAt: new Date('2024-03-04'),
      expiresAt: null,
      urlFingerprint: generateFingerprint('https://naukrigulf.com/jobs/ng-004'),
    },
    {
      externalId: 'by-005',
      platform: 'bayt' as const,
      title: 'UX/UI Designer',
      companyName: 'Careem',
      companyLogoUrl: 'https://logo.clearbit.com/careem.com',
      location: 'Dubai, UAE',
      isRemote: true,
      salaryMin: 80000,
      salaryMax: 120000,
      salaryCurrency: 'AED',
      salaryPeriod: 'year',
      description: `Design intuitive interfaces for our ride-hailing and delivery apps. Portfolio required. Experience with Figma and user research. Join a team of 50+ designers across the region.`,
      applicationUrl: 'https://bayt.com/jobs/by-005',
      atsType: 'workday',
      isGhostJob: false,
      postedAt: new Date('2024-03-05'),
      expiresAt: null,
      urlFingerprint: generateFingerprint('https://bayt.com/jobs/by-005'),
    },
    {
      externalId: 'rz-006',
      platform: 'rozee_pk' as const,
      title: 'Backend Developer',
      companyName: 'Daraz Pakistan',
      companyLogoUrl: 'https://logo.clearbit.com/daraz.pk',
      location: 'Karachi, Pakistan',
      isRemote: true,
      salaryMin: 60000,
      salaryMax: 90000,
      salaryCurrency: 'PKR',
      salaryPeriod: 'month',
      description: `Help us scale Daraz's backend infrastructure. We need Node.js/Python developers with 3+ years experience. Strong SQL and MongoDB skills. Join a team of 100+ engineers.`,
      applicationUrl: 'https://rozee.pk/jobs/rz-006',
      atsType: 'workday',
      isGhostJob: false,
      postedAt: new Date('2024-03-06'),
      expiresAt: null,
      urlFingerprint: generateFingerprint('https://rozee.pk/jobs/rz-006'),
    },
    {
      externalId: 'nk-007',
      platform: 'naukri' as const,
      title: 'QA Automation Engineer',
      companyName: 'Flipkart',
      companyLogoUrl: 'https://logo.clearbit.com/flipkart.com',
      location: 'Bengaluru, India',
      isRemote: false,
      salaryMin: 900000,
      salaryMax: 1400000,
      salaryCurrency: 'INR',
      salaryPeriod: 'year',
      description: `Automate testing for Flipkart's mobile and web platforms. Selenium, Python, and Java expertise needed. 4+ years QA automation. Great benefits and growth opportunities.`,
      applicationUrl: 'https://naukri.com/jobs/nk-007',
      atsType: 'workday',
      isGhostJob: false,
      postedAt: new Date('2024-03-07'),
      expiresAt: null,
      urlFingerprint: generateFingerprint('https://naukri.com/jobs/nk-007'),
    },
    {
      externalId: 'uk-008',
      platform: 'reed_co_uk' as const,
      title: 'DevOps Engineer',
      companyName: 'BT Group',
      companyLogoUrl: 'https://logo.clearbit.com/bt.com',
      location: 'London, UK',
      isRemote: true,
      salaryMin: 60000,
      salaryMax: 85000,
      salaryCurrency: 'GBP',
      salaryPeriod: 'year',
      description: `BT Group is hiring a DevOps engineer to manage cloud infrastructure. AWS, Terraform, and Jenkins experience. 5+ years in DevOps. Flexible working arrangements.`,
      applicationUrl: 'https://reed.co.uk/jobs/uk-008',
      atsType: 'icims',
      isGhostJob: false,
      postedAt: new Date('2024-03-08'),
      expiresAt: null,
      urlFingerprint: generateFingerprint('https://reed.co.uk/jobs/uk-008'),
    },
    {
      externalId: 'stp-009',
      platform: 'stepstone' as const,
      title: 'Frontend Developer',
      companyName: 'SoundCloud',
      companyLogoUrl: 'https://logo.clearbit.com/soundcloud.com',
      location: 'Berlin, Germany',
      isRemote: true,
      salaryMin: 70000,
      salaryMax: 110000,
      salaryCurrency: 'EUR',
      salaryPeriod: 'year',
      description: `Build web experiences for millions of music listeners. React, TypeScript, and modern CSS required. 3+ years frontend experience. Relocation support available.`,
      applicationUrl: 'https://stepstone.de/jobs/stp-009',
      atsType: 'lever',
      isGhostJob: false,
      postedAt: new Date('2024-03-09'),
      expiresAt: null,
      urlFingerprint: generateFingerprint('https://stepstone.de/jobs/stp-009'),
    },
    {
      externalId: 'tt-010',
      platform: 'totaljobs' as const,
      title: 'Product Manager',
      companyName: 'Deliveroo',
      companyLogoUrl: 'https://logo.clearbit.com/deliveroo.com',
      location: 'London, UK',
      isRemote: false,
      salaryMin: 85000,
      salaryMax: 130000,
      salaryCurrency: 'GBP',
      salaryPeriod: 'year',
      description: `Lead product strategy for Deliveroo's marketplace. 4+ years PM experience. Data-driven approach required. Competitive salary and equity package.`,
      applicationUrl: 'https://totaljobs.com/jobs/tt-010',
      atsType: 'greenhouse',
      isGhostJob: false,
      postedAt: new Date('2024-03-10'),
      expiresAt: null,
      urlFingerprint: generateFingerprint('https://totaljobs.com/jobs/tt-010'),
    },
    {
      externalId: 'mn-011',
      platform: 'monster' as const,
      title: 'Senior Software Engineer',
      companyName: 'Microsoft',
      companyLogoUrl: 'https://logo.clearbit.com/microsoft.com',
      location: 'Redmond, WA',
      isRemote: false,
      salaryMin: 170000,
      salaryMax: 230000,
      salaryCurrency: 'USD',
      salaryPeriod: 'year',
      description: `Join Microsoft's cloud division. C++/C# and distributed systems expertise required. 7+ years experience. Lead engineering projects impacting millions of users.`,
      applicationUrl: 'https://microsoft.com/jobs/mn-011',
      atsType: 'workday',
      isGhostJob: false,
      postedAt: new Date('2024-03-11'),
      expiresAt: null,
      urlFingerprint: generateFingerprint('https://microsoft.com/jobs/mn-011'),
    },
    {
      externalId: 'lv-012',
      platform: 'lever' as const,
      title: 'Machine Learning Engineer',
      companyName: 'OpenAI',
      companyLogoUrl: 'https://logo.clearbit.com/openai.com',
      location: 'San Francisco, CA',
      isRemote: false,
      salaryMin: 200000,
      salaryMax: 300000,
      salaryCurrency: 'USD',
      salaryPeriod: 'year',
      description: `Work on cutting-edge AI models. Strong Python, PyTorch, and ML fundamentals required. PhD or equivalent research experience. Equity and competitive benefits.`,
      applicationUrl: 'https://openai.com/jobs/lv-012',
      atsType: 'lever',
      isGhostJob: false,
      postedAt: new Date('2024-03-12'),
      expiresAt: null,
      urlFingerprint: generateFingerprint('https://openai.com/jobs/lv-012'),
    },
  ];

  for (const job of jobs) {
    await prisma.jobListing.create({
      data: job,
    });
  }

  console.log(`✅ Seeded ${jobs.length} job listings`);
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
